### ISSUE TITLE
Integration with MongoDB

### ISSUE THREAD

**Issue by agrcom** [Respekto/posesor#7]
Tutorial from spring.io: https://spring.io/guides/gs/accessing-data-mongodb/

AC:
- application should be able to open connection with MongoDB
- save POST data from Payment API

**Comment by siudeks** [comment]
MongoDb seems to be a good choice, because we need to start application without database initialization

**Comment by agrcom** [comment]
how to for me :) http://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-nosql.html#boot-features-mongodb

**Comment by agrcom** [comment]
Task Done, now posesor-paymentas is able to comunicate with mongo container
